### ISSUE TITLE
Előlegszámla készítése

### ISSUE THREAD

**Issue by ravencs** [szabolcsmaj/DBS#4]
Kéne olyan funkcionalitás, hogy előlegszámla:

A számla felépítése hasonló a normális számlához, az alján viszont az szerepel, hogy mely termékhez fizetett előleget.

A végszámla amit egy előlegszámlához készítünk lezárja az előlegszámlát. Az alján szövegesen szerepeltetni kell a teljes eredeti összeget valamint az előlegszámla tételeit mínusz előjellel.

Specifikáció:
- Előlegszámla működése: ABC ügyfél befizet 50 millió előlegszámlát. Ekkor még nem kap semmit mivel ezt akkor használjuk ha a terméket még nem tudjuk átadni az ügyfélnek. Tételként kerülhet rá konkrét termék de kerülhet rá egy egyedi sor is (pl az, hogy "Szerződés szerinti előleg"). Ha pl rendel 20 millióért Gladiatort, 30 millióért műtrágyát és megjön a Gladiator akkor ha elkészült a szállítólevél akkor készülhet egy Végszámla amihez egyszerre kell csatolni az adott előlegszámlát illetve az adott szállítólevelet. Az előlegszámla lehet, hogy egy ideig csak részlegesen lesz feldolgozva, pl az előbbi esetben maradna 30 millió még az ügyfél "bankjában".
- Előlegszámla készítése és listázása külön ablak az "Értékesítés" menüben. Itt egy lista jönne fel amit lehetne szűrni ügyfél és státusz alapján alapján. Státusz lehet az, hogy felhasználatlan, részlegesen felhasznált vagy teljesen felhasznált/lezárt.
- Ugyanúgy kell szerepelnie a "Szállítólevelek feldolgozása" -> "Számla" menüponton belül. Itt ki lehetne választani, hogy előlegszámláról szeretnénk behúzni
- Egy végszámlához mindig tartozik egy előlegszámla és egy szállítólevél

Az előlegszámlához is kell sztornó, helyesbítés, összegzés mint a sima számláknál

**Comment by szabolcsmaj** [comment]
## További infó:
- Lehetséges, hogy több tétel is szerepelhet egy előlegszámlán. Annyival kell kiegészíteni a meglévő számlakészítés menetét, hogy a termékek hozzáadásán kívül lehessen egyedi sort is rögzíteni. Ezt egy "Egyedi tétel hozzáadása" gombbal lehetne megoldani ahol egy tétel szöveget és összeget kéne csak megadni. Az utóbbi megadása esetén fontos, hogy ez adatbázis módosításokkal is jár. (lásd: #11 )
- A végszámlán fel kell tűntetni az előlegszámla azonosító számát, az előlegszámláról felhasznált összeget a tételeknél illetve az előlegszámlán fennmaradó összeget. A következő linken megtekinthető 2 végszámla (alul a korábbi, fent a később készült): https://www.dropbox.com/s/y3cyut5413jkg2r/el%C5%91legsz%C3%A1mla.pdf?dl=0
- Az előlegszámla adatlapján fel kell tűntetni az előlegszámlához tartozó végszámlákat is, ezen felül a fejléc résznél a teljes összegből fennmaradó összeget. _Nem_ kell tétel szinten lebontani, hogy melyikből mennyi lett felhasználva.
